name: eopf-zarr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - xarray
  - xarray-eopf
  - folium
  - graphviz
  - mapclassify
  - matplotlib=3.10.0
  - matplotlib-inline=0.1.7
  - bottleneck=1.4.2
  - fsspec
  - numpy=1.26.4
  - mystmd
  - cartopy
  - gdal
  - jupyterlab-myst
  - python-graphviz
  - pystac-client
  - zarr
  - tqdm
  - geopandas
  - dask
  - rioxarray
  - pip
