DatasetAttribution:
  - "© by Brockmann Consult GmbH 2025"
  - "© by EOPF Sample Service team and contributors"

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: xcube_eopf_webinar
    StoreId: memory
    StoreParams:
      root: data
    Datasets:
      - Path: sen2_etna_cube.levels
        Title: Sentinel-2 L2A Etna
        Identifier: sen2_etna_cube
        Style: S2L2A

Styles:
  - Identifier: S2L2A
    ColorMappings:
      b02:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      scl:
        ColorBar: sen2_l2a_scl

CustomColorMaps:
  - Identifier: sen2_l2a_scl
    Type: categorical
    Colors:
      - [0, "#000000", No Data (Missing data)]
      - [1, "#ff0000", Saturated or defective pixel]
      - [2, "#2f2f2f", Topographic casted shadows]
      - [3, "#643200", Cloud shadows]
      - [4, "#00a000", Vegetation]
      - [5, "#ffe65a", Not-vegetated]
      - [6, "#0000ff", Water]
      - [7, "#808080", Unclassified]
      - [8, "#c0c0c0", Cloud medium probability]
      - [9, "#ffffff", Cloud high probability]
      - [10, "#64c8ff", Thin cirrus]
      - [11, "#ff96ff", Snow or ice]
    

ServiceProvider:
  ProviderName: "Brockmann Consult GmbH"
  ProviderSite: "https://www.brockmann-consult.de"
  ServiceContact:
    IndividualName: "Konstantin Ntokas"
    PositionName: "Software Engineer"
    ContactInfo:
      Address:
        Street: "Chrysanderstraße 1"
        City: "Hamburg"
        PostalCode: "21029"
        Country: "Germany"
        ElectronicMailAddress: "konstantin.ntokas@brockmann-consult.de"
